[versions]
java = "17"
kotlin = "2.3.0"
agp = "9.0.0"
android-minSDK = "23"
android-compileSDK = "36"
androidx-lifecycle = "2.10.0"
androidx-navigation = "2.9.7"
moshi = "1.15.2"

[libraries]
androidx-core = "androidx.core:core-ktx:1.17.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-test-junit = "androidx.test.ext:junit:1.3.0"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.7.0"
diffUtils = { module = "io.github.java-diff-utils:java-diff-utils", version = "4.16" }
google-material = "com.google.android.material:material:1.13.0"
junit-bom = { module = "org.junit:junit-bom", version = "6.0.2" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
robolectric = "org.robolectric:robolectric:4.16.1"

[plugins]
android = { id = "com.android.application", version.ref = "agp" }
android-lib = { id = "com.android.library", version.ref = "agp" }
android-multiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
android-baseline = { id = "androidx.baselineprofile", version = "1.5.0-alpha01" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.7" }
dokka = { id = "org.jetbrains.dokka-javadoc", version = "2.1.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version = "2.3.4" }
kotlin-samReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
gitVersion = { id = "io.github.gmazzo.gitversion", version = "1.5.1" }
gradle-multiapi = { id = "io.github.gmazzo.gradle.multiapi", version = "1.1.0" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
gradle-testkit-jacoco = { id = "io.github.gmazzo.gradle.testkit.jacoco", version = "1.0.5" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
publicationsReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
